spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 425081836362-aci2p7u8clbrbdug54recc8mtgqdrd9j.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
